### ISSUE TITLE
Write POV statements

### ISSUE THREAD

**Issue by DaGev** [DaGev/ISDM-Assessment#3]
Write Point Of View aka User Stories from the perspectives of the customer and RMs.

**Comment by mherrera1** [comment]
POV statements have been listed for both the inbound and outbound calls, as well as for RM and Customers' perspectives.

**Comment by mherrera1** [comment]
1192917eca7c587e88a2ca39be14c803571fb660 and 0a13c427c663aed6298e5da658a48474c385b715 are the commits which solved the issue.
