### ISSUE TITLE
Make Assumptions

### ISSUE THREAD

**Issue by DaGev** [DaGev/ISDM-Assessment#4]
Make necessary assumptions on the system. These assumptions should clear up any ambiguities associated with the requirements.

**Comment by aminul4184** [comment]
Assumptions issues has been completed

**Comment by aminul4184** [comment]
close issue

**Comment by aminul4184** [comment]
ae624fba299dcb7619794d18ca4a07a6c7d018a5 Assumptions issues that has been closed
